name: overlay_kit
description: A flutter package that have a loading progress,toast message and some future extension.
version: 1.0.6
homepage: https://github.com/Mto292/overlay_kit.git

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  back_button_interceptor: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

