name: store_deploy
on:
  push:
    branches: ["prod"]
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{secrets.FLUTTER_VERSION}}
          channel: 'stable'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true
      - name: Install Dependencies
        run: gem install bundler && bundle install
      - name: Publish to pub.dev
        run: dart pub publish


